services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: quirino
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: pabd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: quirino@admin.com
      PGADMIN_DEFAULT_PASSWORD: quirino123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
